d: 768
output: ../../output/knn
index:
  prod:
    - 'IVF64,PQ8' #good
nprobe:
  prod:
    - 64
  non-prod:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 128
k: 50
metric: METRIC_INNER_PRODUCT
### original 
# index_shard_size: 50000000 # 50M
# query_batch_size: 50000000 # 50M
# evaluation_sample: 10000
# training_sample: 1572864 # 16777216 # 33554432 # 4194304
index_shard_size: 50 # 50M
query_batch_size: 50 # 50M
evaluation_sample: 50
training_sample: 694 # 16777216 # 33554432 # 4194304

datasets:
  b3g:
    root: ../../output/embed/b3g_large/tokenizer-facebook_contriever_msmarco/seq_len-5100/chunk_len-510/model-facebook_contriever_msmarco/
    size: 6946
    files:
    - dtype: float32
      format: raw
      name: chunk.jsonl.npy
      size: 6946

